parameters:
    cache_adapter: 'cache.adapter.filesystem'

framework:
    cache:
        app: cache.adapter.filesystem

when@dev:
    parameters:
        cache_adapter: 'cache.adapter.array'
    framework:
        cache:
            app: cache.adapter.array